# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shakesapp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='shakesapp.proto',
  package='shakesapp',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fshakesapp.proto\x12\tshakesapp\"*\n\x13ShakespeareResponse\x12\x13\n\x0bmatch_count\x18\x01 \x01(\x03\"#\n\x12ShakespeareRequest\x12\r\n\x05query\x18\x01 \x01(\t2f\n\x12ShakespeareService\x12P\n\rGetMatchCount\x12\x1d.shakesapp.ShakespeareRequest\x1a\x1e.shakesapp.ShakespeareResponse\"\x00\x62\x06proto3'
)




_SHAKESPEARERESPONSE = _descriptor.Descriptor(
  name='ShakespeareResponse',
  full_name='shakesapp.ShakespeareResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='match_count', full_name='shakesapp.ShakespeareResponse.match_count', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=72,
)


_SHAKESPEAREREQUEST = _descriptor.Descriptor(
  name='ShakespeareRequest',
  full_name='shakesapp.ShakespeareRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='shakesapp.ShakespeareRequest.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=109,
)

DESCRIPTOR.message_types_by_name['ShakespeareResponse'] = _SHAKESPEARERESPONSE
DESCRIPTOR.message_types_by_name['ShakespeareRequest'] = _SHAKESPEAREREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ShakespeareResponse = _reflection.GeneratedProtocolMessageType('ShakespeareResponse', (_message.Message,), {
  'DESCRIPTOR' : _SHAKESPEARERESPONSE,
  '__module__' : 'shakesapp_pb2'
  # @@protoc_insertion_point(class_scope:shakesapp.ShakespeareResponse)
  })
_sym_db.RegisterMessage(ShakespeareResponse)

ShakespeareRequest = _reflection.GeneratedProtocolMessageType('ShakespeareRequest', (_message.Message,), {
  'DESCRIPTOR' : _SHAKESPEAREREQUEST,
  '__module__' : 'shakesapp_pb2'
  # @@protoc_insertion_point(class_scope:shakesapp.ShakespeareRequest)
  })
_sym_db.RegisterMessage(ShakespeareRequest)



_SHAKESPEARESERVICE = _descriptor.ServiceDescriptor(
  name='ShakespeareService',
  full_name='shakesapp.ShakespeareService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=111,
  serialized_end=213,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetMatchCount',
    full_name='shakesapp.ShakespeareService.GetMatchCount',
    index=0,
    containing_service=None,
    input_type=_SHAKESPEAREREQUEST,
    output_type=_SHAKESPEARERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SHAKESPEARESERVICE)

DESCRIPTOR.services_by_name['ShakespeareService'] = _SHAKESPEARESERVICE

# @@protoc_insertion_point(module_scope)
